site_name: 技術の定点観測
site_description: 気楽にドヤろうぜ
site_author: K.Himeno

theme: windmill

repo_name: Himenon/himenon.github.io
repo_url: https://github.com/Himenon/himenon.github.io
edit_uri: edit/seed/src

extra:
  logo: assets/images/icon.jpg
  version: 混沌期
  article_nav_top: false

extra_css:
  - assets/css/font.css

extra_javascript:
  - assets/js/mermaid.min.js

docs_dir: src
site_dir: docs

google_analytics: ['UA-55455343-7', 'himenon.github.io']

markdown_extensions:
  - admonition
  - markdown_include.include:
      base_path: src
  - toc:
      permalink: true
